on: [push]

name: Build Pure Rust

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - "python"
          - "default"
          - "default,romfs"
          - "image"
          - "image,python"
          - "compression"
          - "compression,python"
          - "map_bg"
          - "map_bg,python"
          - "kao"
          - "kao,python"
          - "map_bg,kao"
          - "map_bg,kao,python"
          - "strings"
          - "strings,python"
          - "dse"
          - "dse,python"
          - "romfs"
          - "strings,map_bg,kao,python,python,with_pmd_wan,dse"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --features=${{ matrix.features }}
