on: [ push ]

name: Build Pure Rust

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - "python"
          - "default"
          - "default,romfs"
          - "image"
          - "image,python"
          - "compression"
          - "compression,python"
          - "map_bg"
          - "map_bg,python"
          - "kao"
          - "kao,python"
          - "map_bg,kao"
          - "map_bg,kao,python"
          - "misc_graphics"
          - "misc_graphics,python"
          - "dungeon_graphics"
          - "dungeon_graphics,python"
          - "strings"
          - "strings,python"
          - "mappa_bin"
          - "mappa_bin,python"
          - "md"
          - "md,python"
          - "item_p"
          - "item_p,python"
          - "waza_p"
          - "waza_p,python"
          - "romfs"
          - "sir0"
          - "script_var_table"
          - "script_var_table,python"
          - "strings,map_bg,kao,python,python,with_pmd_wan,dungeon_graphics,misc_graphics,romfs,sir0"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --no-default-features --features=${{ matrix.features }}
