on: [push]

name: Build Pure Rust

jobs:
  build_with_python:
    name: Build Release with PyO3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
  build_with_no_python:
    name: Build Release without PyO3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --release --features no-python
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features no-python
