on: [ push ]

name: Build Pure Rust

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - "default"
          - "default,romfs"
          - "image"
          - "compression"
          - "map_bg"
          - "kao"
          - "map_bg,kao"
          - "misc_graphics"
          - "dungeon_graphics"
          - "strings"
          - "mappa_bin"
          - "md"
          - "item_p"
          - "waza_p"
          - "romfs"
          - "sir0"
          - "script_var_table"
          - "strings,map_bg,kao,with_pmd_wan,dungeon_graphics,misc_graphics,romfs,sir0"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --no-default-features --features=${{ matrix.features }}
